version: "3.5"
services:
  sonarr:
    container_name: ${PLEXFLIX_COMPANION_PROJECT_NAME}-sonarr
    environment:
      - PUID=${PLEXFLIX_COMPANION_USER}
      - PGID=${PLEXFLIX_COMPANION_GROUP}
      - TZ=${PLEXFLIX_COMPANION_TIMEZONE}
    image: linuxserver/sonarr:latest
    networks:
      - plexflix-companion
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    volumes:
      - ${SONARR_CONFIG_PATH}:/config:delegated
      - ${PLEXFLIX_COMPANION_LIBRARIES_MOUNT_PATH}:/libraries:shared
      - ${PLEXFLIX_COMPANION_DOWNLOADS_PATH}:/downloads:delegated
