version: "3.5"
services:
  sonarr:
    container_name: ${PROJECT_NAME}-sonarr
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TIMEZONE}
    image: linuxserver/sonarr:latest
    networks:
      - plexflix-companion
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    volumes:
      - ${SONARR_CONFIG_PATH}:/config:delegated
      - ${LIBRARIES_MOUNT_PATH}:/libraries:shared
      - ${DOWNLOADS_PATH}:/downloads:delegated
