version: "3.5"
services:
  tautulli:
    container_name: ${PROJECT_NAME}-tautulli
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TIMEZONE}
    image: linuxserver/tautulli:latest
    networks:
      - plexflix-companion
    ports:
      - ${TAUTULLI_PORT}:8181
    restart: unless-stopped
    volumes:
      - ${TAUTULLI_CONFIG_PATH}:/config:delegated
