version: "3.5"
services:

  fuse-shared-mount:
    build:
      context: ./fuse-shared-mount
    container_name: fuse-shared-mount
    image: plexflix-companion/fuse-shared-mount:latest
    networks:
      - plexflix-companion
    pid: host
    privileged: true

  nzbget:
    build:
      context: ./nzbget
    container_name: nzbget
    env_file:
      - .env
    expose:
      - 6789
    image: plexflix-companion/nzbget:latest
    networks:
      - plexflix-companion

  radarr:
    build:
      context: ./radarr
    container_name: radarr
    env_file:
      - .env
    expose:
      - 7878
    image: plexflix-companion/radarr:latest
    networks:
      - plexflix-companion

  rclone:
    build:
      context: ./rclone
    cap_add:
      - MKNOD
      - SYS_ADMIN
    container_name: rclone
    devices:
      - /dev/fuse
    env_file:
      - .env
    healthcheck:
      test: "[ -f /data/.mountcheck ] && exit 0 || exit 1"
      interval: 10s
      timeout: 10s
      start_period: 10s
    image: plexflix-companion/rclone:latest
    networks:
      - plexflix-companion
    security_opt:
      - apparmor:unconfined

  sonarr:
    build:
      context: ./sonarr
    container_name: sonarr
    env_file:
      - .env
    expose:
      - 8989
    image: plexflix-companion/sonarr:latest
    networks:
      - plexflix-companion

  tautulli:
    build:
      context: ./tautulli
    container_name: tautulli
    env_file:
      - .env
    expose:
      - 8181
    image: plexflix-companion/tautulli:latest
    networks:
      - plexflix-companion

networks:
  plexflix-companion:
    driver: bridge
    name: plexflix-companion
