version: "3.5"

services:
  fuse-shared-mount:
    build:
      context: ./fuse-shared-mount
    container_name: ${PLEXFLIX_COMPANION_PROJECT_NAME}-fuse-shared-mount
    image: ${PLEXFLIX_COMPANION_PROJECT_NAME}/fuse-shared-mount:latest
    networks:
      - plexflix-companion
    pid: host
    privileged: true

  list:
    container_name: ${PLEXFLIX_COMPANION_PROJECT_NAME}-list
    command: sh -c "ls -adl /mount/**/*"
    image: alpine:latest
    networks:
      - plexflix-companion
    volumes:
      - ${PLEXFLIX_COMPANION_LIBRARIES_MOUNT_PATH}:/mount:shared
