version: "3.5"
services:
  radarr:
    container_name: ${PROJECT_NAME}-radarr
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TIMEZONE}
    image: linuxserver/radarr:latest
    networks:
      - plexflix-companion
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    volumes:
      - ${RADARR_CONFIG_PATH}:/config:delegated
      - ${LIBRARIES_MOUNT_PATH}:/libraries:shared
      - ${DOWNLOADS_PATH}:/downloads:delegated
