version: "3.5"
services:
  nzbget:
    container_name: ${PROJECT_NAME}-nzbget
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - TZ=${TIMEZONE}
    image: linuxserver/nzbget:latest
    networks:
      - plexflix-companion
    ports:
      - ${NZBGET_PORT}:6789
    restart: unless-stopped
    volumes:
      - ${NZBGET_CONFIG_PATH}:/config:delegated
      - ${DOWNLOADS_PATH}:/downloads:delegated
